POST https://localhost:7040/modules
Content-Type: application/json

{
    "name": "Hekasi Grade 1",
    "description": "History module for Grade 1 students.. ",
    "createdby": "Test User 1",
    "startDateTime": "2022-11-28T08:00:00",
    "endDateTime": "2022-11-28T11:00:00",
    "tags": [
        "Hekasi",
        "History",
        "Grade 1",
        "Primary Education"
    ]
}


###

GET https://localhost:7040/Modules/6402d784-335c-4bc9-8d64-60b32ce981ad